unique_ids:
  assets:
    standard-page.html: HTT2ILEGMPVOIVXZBWDSTG6RRU2VTZKL
    theme.css: HVNZP47VFK4GIKLOXB34JJ6K4DVXLBFH
  forms:
    Form1: SAAUOIACNOVGA2RXGGAIBATJOWXBIGO3
  modules: {}
  scripts: {}
  server_modules: {}
